In [1]:
import pandas as pd
import numpy as np
from functools import reduce
import seaborn as sns
import yaml

In [2]:
with open("../config.yaml", "r") as file:
    config = yaml.safe_load(file)

In [3]:
df_cc = pd.read_csv(config['data']['clean']['file1'], quotechar='"', sep = ";")
df_hu = pd.read_csv(config['data']['clean']['file2'], quotechar='"', sep = ";")
df_pp = pd.read_csv(config['data']['clean']['file3'], quotechar='"', sep = ";")
df_qq = pd.read_csv(config['data']['clean']['file4'], quotechar='"', sep = ";")
df_rr = pd.read_csv(config['data']['clean']['file5'], quotechar='"', sep = ";")
df_sd = pd.read_csv(config['data']['clean']['file6'], quotechar='"', sep = ";")
df_ss = pd.read_csv(config['data']['clean']['file7'], quotechar='"', sep = ";")
df_tg = pd.read_csv(config['data']['clean']['file8'], quotechar='"', sep = ";")
df_tn = pd.read_csv(config['data']['clean']['file9'], quotechar='"', sep = ";")
df_tx = pd.read_csv(config['data']['clean']['file10'], quotechar='"', sep = ";")

In [4]:
all_data = reduce(lambda  left,right: pd.merge(left,right,on=['date'],how='outer'), [df_cc,df_hu,df_pp, df_qq,df_rr,df_sd,df_ss,df_tg,df_tn,df_tx])
all_data.date  = pd.to_datetime(all_data.date, format='%Y-%m-%d')

In [5]:
all_data["year"] = all_data["date"].dt.year
all_data["day_of_year"] = all_data["date"].dt.dayofyear
all_data["doy_sin"] = np.sin(2 * np.pi * all_data["day_of_year"] / 365.25)
all_data["doy_cos"] = np.cos(2 * np.pi * all_data["day_of_year"] / 365.25)
all_data["tx_lag1"] = all_data["tx"].shift(1)
all_data["tx_lag3"] = all_data["tx"].shift(3)
all_data["tx_lag7"] = all_data["tx"].shift(7)

all_data["tn_lag1"] = all_data["tn"].shift(1)
all_data["tg_lag1"] = all_data["tg"].shift(1)

all_data["pp_lag1"] = all_data["pp"].shift(1)
all_data["hu_lag1"] = all_data["hu"].shift(1)
all_data["rr_lag1"] = all_data["rr"].shift(1)
all_data["cc_lag1"] = all_data["cc"].shift(1)
all_data = all_data.dropna()

In [11]:
all_data

,date,cc,hu,pp,qq,rr,sd,ss,tg,tn,...,doy_cos,tx_lag1,tx_lag3,tx_lag7,tn_lag1,tg_lag1,pp_lag1,hu_lag1,rr_lag1,cc_lag1
7,1979-01-08,8.0,95.0,10187.0,15.0,8.0,0.0,1,2.6,-1.85,...,0.990545,8.50,5.60,2.300000,-5.30,1.5,10252.0,93.0,52.0,8.0
8,1979-01-09,4.0,86.0,10117.0,50.0,72.0,0.0,58,3.7,1.60,...,0.988039,6.85,8.30,1.600000,-1.85,2.6,10187.0,95.0,8.0,8.0
9,1979-01-10,7.0,87.0,9870.0,30.0,21.0,0.0,19,3.3,1.40,...,0.985240,5.20,8.50,1.300000,1.60,3.7,10117.0,86.0,72.0,4.0
10,1979-01-11,1.0,78.0,9896.0,55.0,23.0,0.0,68,2.6,0.30,...,0.982150,4.90,6.85,-0.300000,1.40,3.3,9870.0,87.0,21.0,7.0
11,1979-01-12,3.0,91.0,10065.0,54.0,0.0,1.0,64,0.4,-2.00,...,0.978769,2.90,5.20,5.600000,0.30,2.6,9896.0,78.0,23.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17150,2025-12-27,4.0,84.0,10341.0,35.0,0.0,0.0,33,4.8,1.90,...,0.997329,7.60,6.00,10.800000,3.10,4.8,10295.0,79.0,0.0,8.0
17151,2025-12-28,8.0,75.0,10324.0,12.0,0.0,0.0,0,5.4,3.50,...,0.998438,7.30,6.60,11.500000,1.90,4.8,10341.0,84.0,0.0,4.0
17152,2025-12-29,8.0,76.0,10293.0,12.0,0.0,0.0,0,5.7,4.70,...,0.999251,6.60,7.60,9.666667,3.50,5.4,10324.0,75.0,0.0,8.0
17153,2025-12-30,3.0,83.0,10336.0,42.0,0.0,0.0,47,3.3,1.80,...,0.999769,7.30,7.30,7.833333,4.70,5.7,10293.0,76.0,0.0,8.0
17154,2025-12-31,2.0,94.0,10291.0,33.0,0.0,0.0,29,0.9,-1.10,...,0.999991,6.70,6.60,6.000000,1.80,3.3,10336.0,83.0,0.0,3.0

In [12]:
df_hw = all_data.drop(columns='date')

In [13]:
# sns.heatmap(df_ad.corr(), annot=True)
df_hw.corr()

,cc,hu,pp,qq,rr,sd,ss,tg,tn,tx,...,doy_cos,tx_lag1,tx_lag3,tx_lag7,tn_lag1,tg_lag1,pp_lag1,hu_lag1,rr_lag1,cc_lag1
cc,1.000000,0.263439,0.241411,-0.017068,-0.002080,0.012584,0.046563,0.079597,0.086026,0.060055,...,-0.085900,0.064245,0.063180,0.055908,0.067924,0.071253,0.115195,0.101542,-0.002062,0.375240
hu,0.263439,1.000000,0.687303,0.000436,0.001465,0.065653,-0.022122,-0.002888,0.001967,-0.004956,...,0.001552,-0.004275,0.001134,0.003394,-0.002650,-0.004096,0.260510,0.314784,-0.000985,0.098212
pp,0.241411,0.687303,1.000000,-0.005020,-0.004107,0.044336,0.013051,0.008568,0.006908,0.015412,...,-0.006800,0.010950,0.009872,0.019452,0.002880,0.006553,0.292899,0.240214,-0.004740,0.074851
qq,-0.017068,0.000436,-0.005020,1.000000,-0.011786,-0.083273,0.044723,0.010489,0.016436,-0.000511,...,-0.035742,0.000860,0.000590,0.003502,0.018216,0.010839,-0.005292,0.000405,-0.011427,-0.017028
rr,-0.002080,0.001465,-0.004107,-0.011786,1.000000,-0.006421,-0.035847,-0.018927,-0.016845,-0.018406,...,0.045898,-0.016376,-0.015347,-0.019825,-0.019537,-0.019306,-0.002972,-0.000744,0.833760,-0.003538
sd,0.012584,0.065653,0.044336,-0.083273,-0.006421,1.000000,-0.070067,-0.192527,-0.179650,-0.184778,...,0.217757,-0.184243,-0.180928,-0.179248,-0.176520,-0.190419,0.043819,0.065175,-0.006579,0.005445
ss,0.046563,-0.022122,0.013051,0.044723,-0.035847,-0.070067,1.000000,0.400748,0.229998,0.473140,...,-0.457315,0.496573,0.414281,0.368248,0.320261,0.401560,-0.001725,-0.019391,-0.016320,0.046241
tg,0.079597,-0.002888,0.008568,0.010489,-0.018927,-0.192527,0.400748,1.000000,0.957678,0.932908,...,-0.799608,0.964895,0.893566,0.807897,0.882228,0.952698,0.011869,-0.004024,-0.018234,0.066757
tn,0.086026,0.001967,0.006908,0.016436,-0.016845,-0.179650,0.229998,0.957678,1.000000,0.841112,...,-0.728265,0.874130,0.850803,0.762555,0.886068,0.921983,0.012373,0.003495,-0.013803,0.072548
tx,0.060055,-0.004956,0.015412,-0.000511,-0.018406,-0.184778,0.473140,0.932908,0.841112,1.000000,...,-0.811180,0.941182,0.855478,0.786854,0.807524,0.891706,0.013829,-0.008339,-0.019709,0.055126
year,-0.001575,-0.041656,-0.037965,-0.471264,0.012597,-0.135835,-0.005409,0.104790,0.101729,0.099240,...,0.000977,0.099302,0.099409,0.099919,0.101954,0.104949,-0.037982,-0.041659,0.012589,-0.001582
day_of_year,-0.026650,0.032442,0.030442,0.105152,0.008359,-0.003716,-0.040108,0.222936,0.249165,0.182079,...,0.008329,0.191665,0.212260,0.254429,0.257184,0.232479,0.029790,0.031737,0.008075,-0.027743
doy_sin,0.029492,-0.019896,-0.029691,-0.082819,-0.013413,0.000733,0.037850,-0.331261,-0.365279,-0.272269,...,-0.000664,-0.286204,-0.313805,-0.367768,-0.377743,-0.344990,-0.029802,-0.019865,-0.012619,0.028015
doy_cos,-0.085900,0.001552,-0.006800,-0.035742,0.045898,0.217757,-0.457315,-0.799608,-0.728265,-0.811180,...,1.000000,-0.806355,-0.796001,-0.772478,-0.721856,-0.793776,-0.006292,0.001892,0.046139,-0.086396
tx_lag1,0.064245,-0.004275,0.010950,0.000860,-0.016376,-0.184243,0.496573,0.964895,0.874130,0.941182,...,-0.806355,1.000000,0.892002,0.798415,0.841074,0.932898,0.015418,-0.004954,-0.018421,0.060060
tx_lag3,0.063180,0.001134,0.009872,0.000590,-0.015347,-0.180928,0.414281,0.893566,0.850803,0.855478,...,-0.796001,0.892002,1.000000,0.829694,0.885644,0.935912,0.009443,-0.003079,-0.016224,0.063913
tx_lag7,0.055908,0.003394,0.019452,0.003502,-0.019825,-0.179248,0.368248,0.807897,0.762555,0.786854,...,-0.772478,0.798415,0.829694,1.000000,0.774323,0.820169,0.018868,0.003622,-0.016735,0.061818
tn_lag1,0.067924,-0.002650,0.002880,0.018216,-0.019537,-0.176520,0.320261,0.882228,0.886068,0.807524,...,-0.721856,0.841074,0.885644,0.774323,1.000000,0.957670,0.006903,0.001963,-0.016871,0.086011
tg_lag1,0.071253,-0.004096,0.006553,0.010839,-0.019306,-0.190419,0.401560,0.952698,0.921983,0.891706,...,-0.793776,0.932898,0.935912,0.820169,0.957670,1.000000,0.008571,-0.002887,-0.018949,0.079598
pp_lag1,0.115195,0.260510,0.292899,-0.005292,-0.002972,0.043819,-0.001725,0.011869,0.012373,0.013829,...,-0.006292,0.015418,0.009443,0.018868,0.006903,0.008571,1.000000,0.687303,-0.004105,0.241411
hu_lag1,0.101542,0.314784,0.240214,0.000405,-0.000744,0.065175,-0.019391,-0.004024,0.003495,-0.008339,...,0.001892,-0.004954,-0.003079,0.003622,0.001963,-0.002887,0.687303,1.000000,0.001466,0.263439
rr_lag1,-0.002062,-0.000985,-0.004740,-0.011427,0.833760,-0.006579,-0.016320,-0.018234,-0.013803,-0.019709,...,0.046139,-0.018421,-0.016224,-0.016735,-0.016871,-0.018949,-0.004105,0.001466,1.000000,-0.002078
cc_lag1,0.375240,0.098212,0.074851,-0.017028,-0.003538,0.005445,0.046241,0.066757,0.072548,0.055126,...,-0.086396,0.060060,0.063913,0.061818,0.086011,0.079598,0.241411,0.263439,-0.002078,1.000000

In [16]:
df_hw = df_hw.drop(columns=['pp','rr','sd','tg','tn'])

KeyError: "['pp', 'rr', 'sd', 'tg', 'tn'] not found in axis"

In [17]:
test = df_hw[df_hw.year > 2021]
target = df_hw[df_hw.year <= 2021]
y_train = target.tx
y_test  = test.tx
X_train = target.drop(columns=['tx','year'])
X_test  = test.drop(columns=['tx','year'])

In [18]:
# target= df_ad.tx
# features = df_ad.drop(columns=['tg','tx','tn'])

In [19]:
target

,cc,hu,qq,ss,tx,year,day_of_year,doy_sin,doy_cos,tx_lag1,tx_lag3,tx_lag7,tn_lag1,tg_lag1,pp_lag1,hu_lag1,rr_lag1,cc_lag1
7,8.0,95.0,15.0,1,6.85,1979,8,0.137185,0.990545,8.50,5.60,2.3,-5.30,1.5,10252.0,93.0,52.0,8.0
8,4.0,86.0,50.0,58,5.20,1979,9,0.154204,0.988039,6.85,8.30,1.6,-1.85,2.6,10187.0,95.0,8.0,8.0
9,7.0,87.0,30.0,19,4.90,1979,10,0.171177,0.985240,5.20,8.50,1.3,1.60,3.7,10117.0,86.0,72.0,4.0
10,1.0,78.0,55.0,68,2.90,1979,11,0.188099,0.982150,4.90,6.85,-0.3,1.40,3.3,9870.0,87.0,21.0,7.0
11,3.0,91.0,54.0,64,2.00,1979,12,0.204966,0.978769,2.90,5.20,5.6,0.30,2.6,9896.0,78.0,23.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15690,8.0,97.0,-9999.0,0,11.80,2021,361,-0.073045,0.997329,11.20,10.10,6.3,5.40,7.5,10005.0,99.0,2.0,8.0
15691,8.0,85.0,-9999.0,1,15.30,2021,362,-0.055879,0.998438,11.80,9.70,7.4,5.80,8.5,9921.0,97.0,50.0,8.0
15692,6.0,90.0,-9999.0,0,15.00,2021,363,-0.038696,0.999251,15.30,11.20,11.3,8.20,10.0,9926.0,85.0,12.0,8.0
15693,8.0,88.0,-9999.0,0,15.30,2021,364,-0.021501,0.999769,15.00,11.80,10.5,7.10,11.2,10043.0,90.0,8.0,6.0
15694,7.0,86.0,-9999.0,9,15.70,2021,365,-0.004301,0.999991,15.30,15.30,10.1,9.80,12.4,10126.0,88.0,26.0,8.0

In [ ]:
from sklearn.neighbors import KNeighborsRegressor
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
# X_train, X_test, y_train, y_test = train_test_split(features, target, test_size = 0.20,  random_state=0)

In [ ]:
X_train.shape
normalizer = MinMaxScaler()
normalizer.fit(X_train)
X_train_norm = normalizer.transform(X_train)
X_test_norm = normalizer.transform(X_test)
X_train_norm = pd.DataFrame(X_train_norm, columns = X_train.columns)
X_test_norm = pd.DataFrame(X_test_norm, columns = X_test.columns)

In [ ]:
knn = KNeighborsRegressor()
knn.fit(X_train_norm, y_train)
print(f"The accuracy of the model is {knn.score(X_test_norm, y_test): .2f}")

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
from sklearn.ensemble import BaggingRegressor, RandomForestRegressor,AdaBoostRegressor, GradientBoostingRegressor

forest = RandomForestRegressor(n_estimators=100,
                             max_depth=20)
forest.fit(X_train_norm, y_train)
y_pred_test_rf = forest.predict(X_test_norm)


# print(f"MAE {mean_absolute_error(y_pred_test, y_test): .2f}") # mean(abs(error)) = mean(abs(y_test - y_pred_test))
# print(f"RMSE, {np.sqrt(mean_squared_error(y_pred_test, y_test)): .2f}") # sqrt( mean( (y_test - y_pred_test)^2 ) ) # b0, b1, b2...
print(f"R2 score, {forest.score(X_test_norm, y_test): .2f}")

In [ ]:
df_snow = all_data.drop(columns='date')
df_snow["tn_lag3"] = df_snow["tn"].shift(3)
df_snow["tn_lag7"] = df_snow["tn"].shift(7)
df_snow.dropna()